In [30]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN,Dense
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.datasets import imdb

In [12]:
train=pd.read_csv('c-b.csv')

In [13]:
train.head()

User                               Chatbot  Unnamed: 2
0                        hi       hello! how can i help you today?        NaN
1       just wanted to chat             sure! what's on your mind?        NaN
2  nothing much, just bored   i get that. want to hear a fun fact?        NaN
3            yeah, go ahead  did you know that honey never spoils?        NaN
4         what's your name?              you can call me ChatMate!        NaN

In [14]:
train=train.drop(columns=['Unnamed: 2'],axis=1)

In [15]:
train

User  \
0                                               hi   
1                              just wanted to chat   
2                         nothing much, just bored   
3                                   yeah, go ahead   
4                                what's your name?   
..                                             ...   
780     What’s a good way to make fitness a habit?   
781      Can you help me find sports news updates?   
782    What’s the role of mental health in sports?   
783       Can you help me set up a hydration plan?   
784  How can I track my sleep for better recovery?   

                                              Chatbot   
0                     hello! how can i help you today?  
1                           sure! what's on your mind?  
2                 i get that. want to hear a fun fact?  
3                did you know that honey never spoils?  
4                            you can call me ChatMate!  
..                                                 ...  
780  Schedule it like any other important activity ...  
781  Absolutely! I can suggest websites or apps for...  
782  Mental well-being is just as important as phys...  
783  Yes! Drink water regularly throughout the day,...  
784  Use a sleep tracker or app to monitor your sle...  

[785 rows x 2 columns]

In [16]:
train.columns

Index(['User', 'Chatbot '], dtype='object')

In [21]:
max_features=10000 # vocab_size
user=[]
for row in train.loc[:,'User']:
    user.append(row)
user

['hi',
 'just wanted to chat',
 'nothing much, just bored',
 'yeah, go ahead',
 "what's your name?",
 'how are you?',
 'good morning',
 'do you sleep?',
 'tell me something interesting',
 "what's the weather like?",
 'can you feel emotions?',
 'i’m bored',
 'i want a random fact',
 'another fun fact?',
 'hello there',
 'what can you do?',
 'my app is crashing',
 'how do i reset my password?',
 'how to contact support?',
 'are you a real person?',
 'do you dream?',
 'do you like music?',
 "what's your favorite color?",
 "what's 10 + 5?",
 'tell me a joke',
 'who made you?',
 'are you smart?',
 'do you get tired?',
 'do you eat food?',
 'do you play games?',
 'give me a quote',
 'how do I update my profile?',
 'what’s your job?',
 'do you have friends?',
 'tell me something random',
 "what's the capital of France?",
 'how old are you?',
 'are you a robot?',
 'can you help me learn coding?',
 'what’s the meaning of life?',
 'can you dance?',
 'are you always online?',
 'do you speak other

In [22]:
voc_size=10000
one_hot_repr=[one_hot(words,voc_size) for words in user]
one_hot_repr

[[9487],
 [8966, 1433, 3577, 5941],
 [3478, 4725, 8966, 7384],
 [167, 7524, 8495],
 [8940, 9677, 8292],
 [6597, 9205, 6949],
 [4219, 4291],
 [5135, 6949, 2605],
 [973, 75, 4879, 5010],
 [8940, 8779, 5634, 5957],
 [3981, 6949, 656, 3646],
 [1323, 7384],
 [2925, 3890, 2842, 2721, 7759],
 [7092, 4374, 7759],
 [1302, 1419],
 [9373, 3981, 6949, 5135],
 [7001, 2042, 270, 2742],
 [6597, 5135, 2925, 3518, 7001, 5106],
 [6597, 3577, 3037, 9511],
 [9205, 6949, 2842, 8313, 5843],
 [5135, 6949, 4474],
 [5135, 6949, 5957, 4820],
 [8940, 9677, 6919, 237],
 [8940, 4598, 7204],
 [973, 75, 2842, 7063],
 [1568, 3548, 6949],
 [9205, 6949, 1477],
 [5135, 6949, 8616, 9108],
 [5135, 6949, 1597, 2142],
 [5135, 6949, 2165, 9953],
 [6333, 75, 2842, 9906],
 [6597, 5135, 2925, 1160, 7001, 3894],
 [439, 9677, 3492],
 [5135, 6949, 8685, 6],
 [973, 75, 4879, 2721],
 [8940, 8779, 8566, 9291, 5151],
 [6597, 8847, 9205, 6949],
 [9205, 6949, 2842, 4677],
 [3981, 6949, 4520, 75, 5014, 9939],
 [439, 8779, 6404, 9291, 856

In [24]:
sent_len=15
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_len) 

In [25]:
embedded_docs

array([[   0,    0,    0, ...,    0,    0, 9487],
       [   0,    0,    0, ..., 1433, 3577, 5941],
       [   0,    0,    0, ..., 4725, 8966, 7384],
       ...,
       [   0,    0,    0, ..., 8970, 3621,   50],
       [   0,    0,    0, ..., 2842, 6583, 3664],
       [   0,    0,    0, ..., 8957, 7950, 2216]])

In [26]:
dim=10
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_len))
model.compile('adam','mse')

In [27]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 15, 10)            100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [28]:
model.predict(embedded_docs)

25/25 [==============================] - 0s 2ms/step


array([[[-0.04904305,  0.02423667, -0.02418556, ...,  0.00705243,
         -0.02259082,  0.0347384 ],
        [-0.04904305,  0.02423667, -0.02418556, ...,  0.00705243,
         -0.02259082,  0.0347384 ],
        [-0.04904305,  0.02423667, -0.02418556, ...,  0.00705243,
         -0.02259082,  0.0347384 ],
        ...,
        [-0.04904305,  0.02423667, -0.02418556, ...,  0.00705243,
         -0.02259082,  0.0347384 ],
        [-0.04904305,  0.02423667, -0.02418556, ...,  0.00705243,
         -0.02259082,  0.0347384 ],
        [ 0.04329458, -0.00780563,  0.0063375 , ...,  0.04807517,
          0.00122318,  0.0359755 ]],

       [[-0.04904305,  0.02423667, -0.02418556, ...,  0.00705243,
         -0.02259082,  0.0347384 ],
        [-0.04904305,  0.02423667, -0.02418556, ...,  0.00705243,
         -0.02259082,  0.0347384 ],
        [-0.04904305,  0.02423667, -0.02418556, ...,  0.00705243,
         -0.02259082,  0.0347384 ],
        ...,
        [ 0.02638045,  0.03993872, -0.01808587, ...,  

In [29]:
embedded_docs

array([[   0,    0,    0, ...,    0,    0, 9487],
       [   0,    0,    0, ..., 1433, 3577, 5941],
       [   0,    0,    0, ..., 4725, 8966, 7384],
       ...,
       [   0,    0,    0, ..., 8970, 3621,   50],
       [   0,    0,    0, ..., 2842, 6583, 3664],
       [   0,    0,    0, ..., 8957, 7950, 2216]])

## RNN Starts here

In [31]:
## Load the imdb dataset

max_features=10000 ##vocabulary size
(X_train,y_train),(X_test,y_test)=imdb.load_data(num_words=max_features)

# Print the shape of the data
print(f'Training data shape: {X_train.shape}, Training labels shape: {y_train.shape}')
print(f'Testing data shape: {X_train.shape}, Testing labels shape: {y_test.shape}')

17464789/17464789 [==============================] - 4s 0us/step
Training data shape: (25000,), Training labels shape: (25000,)
Testing data shape: (25000,), Testing labels shape: (25000,)


In [32]:
X_train[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 2,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 2,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 2,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 2,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 2,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 2,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5,
 144,
 30,
 5535,
 18,

1